### PR TITLE
Link github repo to the actual rendering library

### PR DESCRIPTION
**Pull request by musaffa**

### CODE REVIEW

**Comment by acorncom** [comment]
@musaffa Much appreciated!  We had this link linking to the Glimmer organization (https://github.com/glimmerjs) but were getting folks who were a bit frustrated about things (and also needed a place for people to file issues).  Could you send in a few links to those various places to put in the Readme instead?

**Comment by locks** [comment]
There's also the question that the glimmer repository by itself isn't that useful, the interesting bits are actually the packages in the glimmerjs org, so it's a bit tricky at the moment.
We are definitely pondering how to best organize things, we still have some repository transfers to do. This to say we are concerned about clarity.

**Comment by musaffa** [comment]
I think this website repository as well as the glimmer library repository should be moved to `glimmerjs` org. I was surprised that when I clicked the github link, the link pointed it to this repository.

**Comment by acorncom** [comment]
Yes, icing this website to the glimmerjs organization is the long-term goal. Just added links in #50

**Pull request closed without merging**
